import { FaXTwitter, FaFacebookF, FaLinkedinIn, FaInstagram } from "react-icons/fa6";

export const teamMembers = [
    {
      imgSrc: "https://www.wsclinic.org/assets/Rajpal-D5bmoC8O.png",
      name: 'Dr. Upinder Kaur',
      title: 'Psychologist',
      delay: '0.6s',
      profileLink: '/Doctors#Psychologist',
      appointmentLink: '/Contact#FixAppointment',
      socialLinks: [
        { href: "#", icon: <FaXTwitter /> },
      { href: "#", icon: <FaFacebookF /> },
      { href: "#", icon: <FaLinkedinIn /> },
      { href: "#", icon: <FaInstagram /> },
      ],
    },
  
    {
      imgSrc: "https://www.wsclinic.org/assets/Rajpal-D5bmoC8O.png",
      name: 'Dr. Amit Harshana',
      title: 'HIV/ AIDS',
      delay: '0.3s',
      profileLink: '/Doctors#General-Physician',
      appointmentLink: '/Contact#FixAppointment',
      socialLinks: [
        { href: "#", icon: <FaXTwitter /> },
        { href: "#", icon: <FaFacebookF /> },
        { href: "#", icon: <FaLinkedinIn /> },
        { href: "#", icon: <FaInstagram /> },
      ],
    },
    {
      imgSrc: "https://www.wsclinic.org/assets/Rajpal-D5bmoC8O.png",
      name: 'Dr. Ankur',
      title: 'Consultant Anesthesiologist',
      delay: '0.6s',
      profileLink: '/Doctors',
      appointmentLink: '/Contact#FixAppointment',
      socialLinks: [
        { href: "#", icon: <FaXTwitter /> },
        { href: "#", icon: <FaFacebookF /> },
        { href: "#", icon: <FaLinkedinIn /> },
        { href: "#", icon: <FaInstagram /> },
      ],
    },
    {
      imgSrc: "https://www.wsclinic.org/assets/Rajpal-D5bmoC8O.png",
      name: 'Dr. Arvind',
      title: 'Psychiatrist',
      delay: '0.1s',
      profileLink: '/Doctors',
      appointmentLink: '/Contact#FixAppointment',
      socialLinks: [
         { href: "#", icon: <FaXTwitter /> },
      { href: "#", icon: <FaFacebookF /> },
      { href: "#", icon: <FaLinkedinIn /> },
      { href: "#", icon: <FaInstagram /> },
      ],
    },
    {
      imgSrc: "https://www.wsclinic.org/assets/Rajpal-D5bmoC8O.png",
      name: 'Dr. Ashish Shah ',
      title: 'Psychiatrist',
      delay: '0.6s',
      profileLink: '/Doctors',
      appointmentLink: '/Contact#FixAppointment',
      socialLinks: [
        { href: "#", icon: <FaXTwitter /> },
      { href: "#", icon: <FaFacebookF /> },
      { href: "#", icon: <FaLinkedinIn /> },
      { href: "#", icon: <FaInstagram /> },
      ],
    },
    {
      imgSrc: "https://www.wsclinic.org/assets/Rajpal-D5bmoC8O.png",
      name: 'Dr. Bhanu Mishra',
      title: 'Nephrologist',
      delay: '0.6s',
      profileLink: '/Doctors#Nephrologist',
      appointmentLink: '/Contact#FixAppointment',
      socialLinks: [
         { href: "#", icon: <FaXTwitter /> },
      { href: "#", icon: <FaFacebookF /> },
      { href: "#", icon: <FaLinkedinIn /> },
      { href: "#", icon: <FaInstagram /> },
      ],
    },
    {
      imgSrc: "https://www.wsclinic.org/assets/Rajpal-D5bmoC8O.png",
      name: 'Dr. Divija Chugh',
      title: 'Gynaecologist',
      delay: '0.6s',
      profileLink: '/Doctors#Gynaecologist',
      appointmentLink: '/Contact#FixAppointment',
      socialLinks: [
         { href: "#", icon: <FaXTwitter /> },
      { href: "#", icon: <FaFacebookF /> },
      { href: "#", icon: <FaLinkedinIn /> },
      { href: "#", icon: <FaInstagram /> },
      ],
    },
    {
      imgSrc: "https://www.wsclinic.org/assets/Rajpal-D5bmoC8O.png",
      name: 'Dr. Harish Chandra ',
      title: 'Psychiatrist',
      delay: '0.6s',
      profileLink: '/Doctors#Psychiatrist',
      appointmentLink: '/Contact#FixAppointment',
      socialLinks: [
         { href: "#", icon: <FaXTwitter /> },
      { href: "#", icon: <FaFacebookF /> },
      { href: "#", icon: <FaLinkedinIn /> },
      { href: "#", icon: <FaInstagram /> },
      ],
    },
    {
      imgSrc: "https://www.wsclinic.org/assets/Rajpal-D5bmoC8O.png",
      name: 'Dr. Madhur Mahna',
      title: 'Orthopaedic',
      delay: '0.6s',
      profileLink: '/Doctors#Orthopaedic',
      appointmentLink: '/Contact#FixAppointment',
      socialLinks: [
         { href: "#", icon: <FaXTwitter /> },
      { href: "#", icon: <FaFacebookF /> },
      { href: "#", icon: <FaLinkedinIn /> },
      { href: "#", icon: <FaInstagram /> },
      ],
    },
    {
      imgSrc: "https://www.wsclinic.org/assets/Rajpal-D5bmoC8O.png",
      name: 'Dr. Manoj Goel',
      title: 'Senior Consultant Physician',
      delay: '0.6s',
      profileLink: '/Doctors',
      appointmentLink: '/Contact#FixAppointment',
      socialLinks: [
         { href: "#", icon: <FaXTwitter /> },
      { href: "#", icon: <FaFacebookF /> },
      { href: "#", icon: <FaLinkedinIn /> },
      { href: "#", icon: <FaInstagram /> },
      ],
    },
    {
      imgSrc: "https://www.wsclinic.org/assets/Rajpal-D5bmoC8O.png",
      name: 'Dr. Naveen Bhamri',
      title: 'General Physician',
      delay: '0.6s',
      profileLink: '/Docters#Cardiologist',
      appointmentLink: '/Contact#FixAppointment',
      socialLinks: [
         { href: "#", icon: <FaXTwitter /> },
      { href: "#", icon: <FaFacebookF /> },
      { href: "#", icon: <FaLinkedinIn /> },
      { href: "#", icon: <FaInstagram /> },
      ],
    },
    {
      imgSrc: "https://www.wsclinic.org/assets/Rajpal-D5bmoC8O.png",
      name: 'Dr. Nitya Subramanian',
      title: 'ENT',
      delay: '0.6s',
      profileLink: '/Docters#ENT/Hearing',
      appointmentLink: '/Contact#FixAppointment',
      socialLinks: [
         { href: "#", icon: <FaXTwitter /> },
      { href: "#", icon: <FaFacebookF /> },
      { href: "#", icon: <FaLinkedinIn /> },
      { href: "#", icon: <FaInstagram /> },
      ],
    },
    {
      imgSrc: "https://www.wsclinic.org/assets/Rajpal-D5bmoC8O.png",
      name: 'Dr. Rajpal Kaushik',
      title: 'Psychologist',
      delay: '0.6s',
      profileLink: '/Docters',
      appointmentLink: '/Contact#FixAppointment',
      socialLinks: [
         { href: "#", icon: <FaXTwitter /> },
      { href: "#", icon: <FaFacebookF /> },
      { href: "#", icon: <FaLinkedinIn /> },
      { href: "#", icon: <FaInstagram /> },
      ],
    },
    {
      imgSrc: "https://www.wsclinic.org/assets/Rajpal-D5bmoC8O.png",
      name: 'Dr. Sachin Rajpal',
      title: 'Plastic & Cosmetic Surgeon',
      delay: '0.6s',
      profileLink: '/Docters#Plastic-Cosmetic-Surgeon',
      appointmentLink: '/Contact#FixAppointment',
      socialLinks: [
         { href: "#", icon: <FaXTwitter /> },
      { href: "#", icon: <FaFacebookF /> },
      { href: "#", icon: <FaLinkedinIn /> },
      { href: "#", icon: <FaInstagram /> },
      ],
    },
    
    {
      imgSrc: "https://www.wsclinic.org/assets/Rajpal-D5bmoC8O.png",
      name: 'Dr. Varun',
      title: 'Child Specialist',
      delay: '0.6s',
      profileLink: '/Docters',
      appointmentLink: '/Contact#FixAppointment',
      socialLinks: [
         { href: "#", icon: <FaXTwitter /> },
      { href: "#", icon: <FaFacebookF /> },
      { href: "#", icon: <FaLinkedinIn /> },
      { href: "#", icon: <FaInstagram /> },
      ],
    },
    {
      imgSrc: "https://www.wsclinic.org/assets/Rajpal-D5bmoC8O.png",
      name: 'Dr. Virat',
      title: 'Physiotherapist',
      delay: '0.6s',
      profileLink: '/Docters',
      appointmentLink: '/Contact#FixAppointment',
      socialLinks: [
         { href: "#", icon: <FaXTwitter /> },
      { href: "#", icon: <FaFacebookF /> },
      { href: "#", icon: <FaLinkedinIn /> },
      { href: "#", icon: <FaInstagram /> },
      ],
    },
  ];